# This file was generated by GoReleaser. DO NOT EDIT.
class BuildTools < Formula
  desc ""
  homepage ""
  version "0.0.22"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/buildtool/build-tools/releases/download/v0.0.22/build-tools_0.0.22_Darwin_x86_64.tar.gz"
    sha256 "cb5f510acbd6c697b30766c2a7c594645f05d0a339eb6cdcf7d1877c3f38f55a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/buildtool/build-tools/releases/download/v0.0.22/build-tools_0.0.22_Linux_x86_64.tar.gz"
      sha256 "069ac8362ebabd2cb97d284fbdc298e2cffb68af8652c78d18f266306bc3fabb"
    end
  end

  def install
    bin.install "build"
    bin.install "push"
    bin.install "deploy"
    bin.install "kubecmd"
  end
end
