# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuildTools < Formula
  desc ""
  homepage "https://buildtools.io/"
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.3/build-tools_0.4.3_Darwin_x86_64.tar.gz"
      sha256 "d270f4e67388dd497f473b63b862521904bf4fcd427b8e162aab71aac34c5d04"

      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.3/build-tools_0.4.3_Darwin_arm64.tar.gz"
      sha256 "9ab58c140d689af3bef93aadf02bceeb784437b12e80ddf33df1152a3522f95f"

      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.3/build-tools_0.4.3_Linux_x86_64.tar.gz"
      sha256 "b34df82356c6d200674eb462fe185b8dec510a04d6156c280b8318a5a0b659a2"
      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.3/build-tools_0.4.3_Linux_arm64.tar.gz"
      sha256 "c0a01be674f54d097fd0cb6f69a13232ec6991bc83e23f26f6bb09fa5954f85d"
      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
  end
end
