# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuildTools < Formula
  desc ""
  homepage "https://buildtools.io/"
  version "0.4.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.6/build-tools_0.4.6_Darwin_x86_64.tar.gz"
      sha256 "6c6ac8a8542603a123cb2b4f4b1e6aa85a512774c74b22b9f4a8d96501f5e810"

      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.6/build-tools_0.4.6_Darwin_arm64.tar.gz"
      sha256 "4624d867e00ba66611a6aececcd0a6fd6ff42a9a0c97b73a0deae26b5f5e4cde"

      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.6/build-tools_0.4.6_Linux_x86_64.tar.gz"
      sha256 "e99abc09f412d2f43c6d5eb129630b0b281e650fc5c69b4ed474d6278d54a091"
      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildtool/build-tools/releases/download/v0.4.6/build-tools_0.4.6_Linux_arm64.tar.gz"
      sha256 "6cfcb9f70028075b82f5d6be258ab4dc93efc3b3044c284d473e000be539da9c"
      def install
        bin.install "build"
        bin.install "push"
        bin.install "deploy"
        bin.install "kubecmd"
        bin.install "promote"
      end
    end
  end
end
