# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc ""
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/buildtool/scaffold/releases/download/v0.0.2/scaffold_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "ee6e36ae6bfb62c520e290520439c91a7f05cbb4414103b95de35c6e7208d38f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/buildtool/scaffold/releases/download/v0.0.2/scaffold_0.0.2_Linux_x86_64.tar.gz"
      sha256 "c54d9d2e0fd41ac5a1fe063193f0c18b84ef97550ff2f174ce1034f986985467"
    end
  end

  def install
    bin.install "scaffold"
  end
end
