# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/buildtool/scaffold/releases/download/v0.0.1/scaffold_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "48a5153855291a25d26278a2655f1eecdf678ea28a9ea6fc1f34102ca8324b19"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/buildtool/scaffold/releases/download/v0.0.1/scaffold_0.0.1_Linux_x86_64.tar.gz"
      sha256 "5a11ed1deb96a905c41d0f14f540846e1a0a630d5b59dce59e91b37bc0bef0e8"
    end
  end

  def install
    bin.install "scaffold"
  end
end
